// Frontend test configuration (test-only; not used by the app build).
// Mirrors the Jest config generated by react-scripts 2.1.8 (scripts/utils/createJestConfig.js)
// and uses react-scripts' own Babel transform. Kept as a separate config (instead of
// `react-scripts test`) so that .env is not loaded: no real Firebase/API keys reach the tests.
// Run with `npm test`.
'use strict';

const cra = (p) => require.resolve(`react-scripts/config/jest/${p}`);

module.exports = {
  rootDir: __dirname,
  roots: ['<rootDir>/src'],
  resolver: require.resolve('jest-pnp-resolver'),
  setupFiles: [require.resolve('react-app-polyfill/jsdom')],
  setupTestFrameworkScriptFile: '<rootDir>/src/setupTests.js',
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}',
    '<rootDir>/src/**/?(*.)(spec|test).{js,jsx,ts,tsx}',
  ],
  testEnvironment: 'jsdom',
  testURL: 'http://localhost',
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': cra('babelTransform.js'),
    '^.+\\.css$': cra('cssTransform.js'),
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': cra('fileTransform.js'),
  },
  transformIgnorePatterns: [
    '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  moduleNameMapper: {
    '^react-native$': 'react-native-web',
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
  },
  moduleFileExtensions: ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'],
};
